trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: 22.x

stages:
  - stage: CI
    displayName: Build Angular UI
    jobs:
      - job: angular
        displayName: Angular UI
        steps:
          - task: NodeTool@0
            displayName: Install Node.js
            inputs:
              versionSpec: $(nodeVersion)

          - script: npm install -g pnpm
            displayName: Install pnpm

          - script: pnpm install --frozen-lockfile
            displayName: Install dependencies

          - script: pnpm run build
            displayName: Build (producción)
